# Generated by Django 3.1 on 2020-09-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='questionTitle',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
