# Generated by Django 3.1 on 2020-09-02 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_post_questiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acceptanceStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
