# Generated by Django 3.1 on 2020-09-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0004_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='questionContent',
        ),
    ]
